package com.example.game.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

//Dia
val morado_primaryLight = Color(0xFF715289)
val morado_onPrimaryLight = Color(0xFFFFFFFF)
val morado_primaryContainerLight = Color(0xFFF2DAFF)
val morado_onPrimaryContainerLight = Color(0xFF2A0C41)
val morado_secondaryLight = Color(0xFF675A6E)
val morado_onSecondaryLight = Color(0xFFFFFFFF)
val morado_secondaryContainerLight = Color(0xFFEEDDF6)
val morado_onSecondaryContainerLight = Color(0xFF211829)
val morado_tertiaryLight = Color(0xFF815156)
val morado_onTertiaryLight = Color(0xFFFFFFFF)
val morado_tertiaryContainerLight = Color(0xFFFFDADB)
val morado_onTertiaryContainerLight = Color(0xFF321015)
val morado_errorLight = Color(0xFFBA1A1A)
val morado_onErrorLight = Color(0xFFFFFFFF)
val morado_errorContainerLight = Color(0xFFFFDAD6)
val morado_onErrorContainerLight = Color(0xFF410002)
val morado_backgroundLight = Color(0xFFFFF7FD)
val morado_onBackgroundLight = Color(0xFF1E1A20)
val morado_surfaceLight = Color(0xFFFFF7FD)
val morado_onSurfaceLight = Color(0xFF1E1A20)
val morado_surfaceVariantLight = Color(0xFFE9DFEA)
val morado_onSurfaceVariantLight = Color(0xFF4B454D)
val morado_outlineLight = Color(0xFF7C757E)
val morado_outlineVariantLight = Color(0xFFCDC3CE)
val morado_scrimLight = Color(0xFF000000)
val morado_inverseSurfaceLight = Color(0xFF332F35)
val morado_inverseOnSurfaceLight = Color(0xFFF7EEF6)
val morado_inversePrimaryLight = Color(0xFFDDB9F7)
val morado_surfaceDimLight = Color(0xFFE0D8DF)
val morado_surfaceBrightLight = Color(0xFFFFF7FD)
val morado_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val morado_surfaceContainerLowLight = Color(0xFFFAF1F9)
val morado_surfaceContainerLight = Color(0xFFF4EBF3)
val morado_surfaceContainerHighLight = Color(0xFFEEE6ED)
val morado_surfaceContainerHighestLight = Color(0xFFE8E0E8)


//Oscuro

val morado_primaryDark = Color(0xFFDDB9F7)
val morado_onPrimaryDark = Color(0xFF402357)
val morado_primaryContainerDark = Color(0xFF583A6F)
val morado_onPrimaryContainerDark = Color(0xFFF2DAFF)
val morado_secondaryDark = Color(0xFFD1C1D9)
val morado_onSecondaryDark = Color(0xFF372C3F)
val morado_secondaryContainerDark = Color(0xFF4E4256)
val morado_onSecondaryContainerDark = Color(0xFFEEDDF6)
val morado_tertiaryDark = Color(0xFFF4B7BB)
val morado_onTertiaryDark = Color(0xFF4C2529)
val morado_tertiaryContainerDark = Color(0xFF663A3F)
val morado_onTertiaryContainerDark = Color(0xFFFFDADB)
val morado_errorDark = Color(0xFFFFB4AB)
val morado_onErrorDark = Color(0xFF690005)
val morado_errorContainerDark = Color(0xFF93000A)
val morado_onErrorContainerDark = Color(0xFFFFDAD6)
val morado_backgroundDark = Color(0xFF151217)
val morado_onBackgroundDark = Color(0xFFE8E0E8)
val morado_surfaceDark = Color(0xFF151217)
val morado_onSurfaceDark = Color(0xFFE8E0E8)
val morado_surfaceVariantDark = Color(0xFF4B454D)
val morado_onSurfaceVariantDark = Color(0xFFCDC3CE)
val morado_outlineDark = Color(0xFF968E98)
val morado_outlineVariantDark = Color(0xFF4B454D)
val morado_scrimDark = Color(0xFF000000)
val morado_inverseSurfaceDark = Color(0xFFE8E0E8)
val morado_inverseOnSurfaceDark = Color(0xFF332F35)
val morado_inversePrimaryDark = Color(0xFF715289)
val morado_surfaceDimDark = Color(0xFF151217)
val morado_surfaceBrightDark = Color(0xFF3C383E)
val morado_surfaceContainerLowestDark = Color(0xFF100D12)
val morado_surfaceContainerLowDark = Color(0xFF1E1A20)
val morado_surfaceContainerDark = Color(0xFF221E24)
val morado_surfaceContainerHighDark = Color(0xFF2D292E)
val morado_surfaceContainerHighestDark = Color(0xFF383339)

//Dia Azul

val azul_primaryLight = Color(0xFF415F91)
val azul_onPrimaryLight = Color(0xFFFFFFFF)
val azul_primaryContainerLight = Color(0xFFD6E3FF)
val azul_onPrimaryContainerLight = Color(0xFF001B3E)
val azul_secondaryLight = Color(0xFF565F71)
val azul_onSecondaryLight = Color(0xFFFFFFFF)
val azul_secondaryContainerLight = Color(0xFFDAE2F9)
val azul_onSecondaryContainerLight = Color(0xFF131C2B)
val azul_tertiaryLight = Color(0xFF705575)
val azul_onTertiaryLight = Color(0xFFFFFFFF)
val azul_tertiaryContainerLight = Color(0xFFFAD8FD)
val azul_onTertiaryContainerLight = Color(0xFF28132E)
val azul_errorLight = Color(0xFFBA1A1A)
val azul_onErrorLight = Color(0xFFFFFFFF)
val azul_errorContainerLight = Color(0xFFFFDAD6)
val azul_onErrorContainerLight = Color(0xFF410002)
val azul_backgroundLight = Color(0xFFF9F9FF)
val azul_onBackgroundLight = Color(0xFF191C20)
val azul_surfaceLight = Color(0xFFF9F9FF)
val azul_onSurfaceLight = Color(0xFF191C20)
val azul_surfaceVariantLight = Color(0xFFE0E2EC)
val azul_onSurfaceVariantLight = Color(0xFF44474E)
val azul_outlineLight = Color(0xFF74777F)
val azul_outlineVariantLight = Color(0xFFC4C6D0)
val azul_scrimLight = Color(0xFF000000)
val azul_inverseSurfaceLight = Color(0xFF2E3036)
val azul_inverseOnSurfaceLight = Color(0xFFF0F0F7)
val azul_inversePrimaryLight = Color(0xFFAAC7FF)
val azul_surfaceDimLight = Color(0xFFD9D9E0)
val azul_surfaceBrightLight = Color(0xFFF9F9FF)
val azul_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val azul_surfaceContainerLowLight = Color(0xFFF3F3FA)
val azul_surfaceContainerLight = Color(0xFFEDEDF4)
val azul_surfaceContainerHighLight = Color(0xFFE7E8EE)
val azul_surfaceContainerHighestLight = Color(0xFFE2E2E9)

//Azul Noche

val azul_primaryDark = Color(0xFFAAC7FF)
val azul_onPrimaryDark = Color(0xFF0A305F)
val azul_primaryContainerDark = Color(0xFF284777)
val azul_onPrimaryContainerDark = Color(0xFFD6E3FF)
val azul_secondaryDark = Color(0xFFBEC6DC)
val azul_onSecondaryDark = Color(0xFF283141)
val azul_secondaryContainerDark = Color(0xFF3E4759)
val azul_onSecondaryContainerDark = Color(0xFFDAE2F9)
val azul_tertiaryDark = Color(0xFFDDBCE0)
val azul_onTertiaryDark = Color(0xFF3F2844)
val azul_tertiaryContainerDark = Color(0xFF573E5C)
val azul_onTertiaryContainerDark = Color(0xFFFAD8FD)
val azul_errorDark = Color(0xFFFFB4AB)
val azul_onErrorDark = Color(0xFF690005)
val azul_errorContainerDark = Color(0xFF93000A)
val azul_onErrorContainerDark = Color(0xFFFFDAD6)
val azul_backgroundDark = Color(0xFF111318)
val azul_onBackgroundDark = Color(0xFFE2E2E9)
val azul_surfaceDark = Color(0xFF111318)
val azul_onSurfaceDark = Color(0xFFE2E2E9)
val azul_surfaceVariantDark = Color(0xFF44474E)
val azul_onSurfaceVariantDark = Color(0xFFC4C6D0)
val azul_outlineDark = Color(0xFF8E9099)
val azul_outlineVariantDark = Color(0xFF44474E)
val azul_scrimDark = Color(0xFF000000)
val azul_inverseSurfaceDark = Color(0xFFE2E2E9)
val azul_inverseOnSurfaceDark = Color(0xFF2E3036)
val azul_inversePrimaryDark = Color(0xFF415F91)
val azul_surfaceDimDark = Color(0xFF111318)
val azul_surfaceBrightDark = Color(0xFF37393E)
val azul_surfaceContainerLowestDark = Color(0xFF0C0E13)
val azul_surfaceContainerLowDark = Color(0xFF191C20)
val azul_surfaceContainerDark = Color(0xFF1D2024)
val azul_surfaceContainerHighDark = Color(0xFF282A2F)
val azul_surfaceContainerHighestDark = Color(0xFF33353A)